### ISSUE TITLE
Fixing environment

### ISSUE THREAD

**Issue by stoeckel4code** [VACILT/MA_visualization#11]
I have problems updating my environment: 

At first the 'solving envirenment' takes more than two hours. then this message says that I would have no permission. @kuchaale Do you know a simple fix, other than completly reinstalling my conda environment?
![image](https://user-images.githubusercontent.com/58188931/121206605-e5aec900-c878-11eb-9e69-765c6c6cb5aa.png)

**Comment by kuchaale** [comment]
Did you try to run it as an administrator?

**Comment by stoeckel4code** [comment]
yes

**Comment by kuchaale** [comment]
Check the same issue [here](https://stackoverflow.com/questions/55290271/updating-anaconda-fails-environment-not-writable-error/55361151). If it does not help, create a new Conda environment for which you don't need admin rights.

**Comment by stoeckel4code** [comment]
I created a new environment. For some reason jupyter notebook doenst works with 'Panel'. When panel is installed it won't start, when removed, everthing works fine.

**Comment by kuchaale** [comment]
Which versions (jupyter and panel) do you use? Can you try one of the hints [here](https://github.com/holoviz/panel/issues/1347)?

**Comment by stoeckel4code** [comment]
jupyter                   1.0.0                    py38_7
jupyter-packaging         0.7.12             pyhd3eb1b0_0
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_console           6.4.0              pyhd3eb1b0_0
jupyter_core              4.7.1            py38haa95532_0
jupyter_server            1.4.1            py38haa95532_0
jupyterlab                3.0.14             pyhd3eb1b0_1
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.4.0              pyhd3eb1b0_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1

panel                     0.11.3             pyhd3eb1b0_0

Also found this issue and tried:
`conda install -c pyviz bokeh==2`
atm, it runs for one hour

**Comment by stoeckel4code** [comment]
after running 'conda update -all' at least it starts the jupyter notebook server.

**Comment by stoeckel4code** [comment]
My notebooks and so on are working completly fine. But The jupyter books don't work, To exclude the possibilty that my content is incorrect, I cloned the [mini-example](https://github.com/executablebooks/quantecon-mini-example). Before the change of my environment it has worked fine. Now, not even this is working. I can't make sense of the error message:
![Unbenannt](https://user-images.githubusercontent.com/58188931/121814921-e3cb7800-cc73-11eb-9cfc-376ae5add334.JPG)

**Comment by kuchaale** [comment]
Can you add any landing page and test it again? Apparently, if the _toc.yml file has no landing page, then there's an unhelpful error spat out (see [here](https://github.com/executablebooks/jupyter-book/issues/1020)). It should be fixed in [v0.11.1](https://github.com/executablebooks/jupyter-book/pull/1321) though.

**Comment by stoeckel4code** [comment]
Ok, I adapted to the new format ([commit](https://github.com/VACILT/MA_visualization/commit/8904ae5aeee4182009116ff33aed7444617a9dd4)). It works for the mini-example but not for our book.

**Comment by kuchaale** [comment]
Still the same problem?

**Comment by stoeckel4code** [comment]
The error message looks similar. I tried making a book only with the intro side and this works. I think the notebooks are the problem or my envirnment to run them

When i try `conda update -all`, this comes up:

![image](https://user-images.githubusercontent.com/58188931/122052314-d7672c80-cde5-11eb-8218-0451380011e5.png)

**Comment by stoeckel4code** [comment]
![image](https://user-images.githubusercontent.com/58188931/122054937-6c6b2500-cde8-11eb-8cce-5a1135486db7.png)

**Comment by kuchaale** [comment]
I am not sure whether `conda update -all` makes sense in this case. Do you have [myst_nb](https://myst-nb.readthedocs.io/en/latest/) installed? If not, please do so: `pip install myst-nb`. 

BTW can you copy your log error in the following instead of screenshots? It helps with copy-pasting.

```markdown
<details><summary>Output of log error</summary>

<!-- Paste the log error here -->

</details>
```

**Comment by stoeckel4code** [comment]
Every time I install a package, there is another one missing.
<details><summary>Output of log error</summary>
Source Folder: D:\project\MA_vis\MA_visualization\book
Config Path: None
Output Path: D:\project\MA_vis\MA_visualization\book\_build\html
←[01mRunning Sphinx v4.0.1←[39;49;00m
←[91mWARNING: cannot override config setting 'html_add_permalinks' with unsupported type, ignoring←[39;49;00m
[etoc] Changing master_doc to 'intro'
←[01mmyst v0.13.7:←[39;49;00m MdParserConfig(renderer='sphinx', commonmark_only=False, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, update_mathjax=True, enable_extensions=['colon_fence', 'dollarmath', 'linkify', 'substitution'], disable_syntax=[], url_schemes=['mailto', 'http', 'https'], heading_anchors=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'])
←[01mbuilding [mo]: ←[39;49;00mtargets for 0 po files that are out of date
←[01mbuilding [html]: ←[39;49;00mtargets for 4 source files that are out of date
←[01mupdating environment: ←[39;49;00m[new config] 4 added, 0 changed, 0 removed
←[01mreading sources... ←[39;49;00m[ 25%] ←[35mdocumentation←[39;49;00m
←[91mException occurred:←[39;49;00m
  File "c:\users\willy\anaconda3\lib\site-packages\markdown_it\rules_core\linkify.py", line 32, in linkify
    raise ModuleNotFoundError("Linkify enabled but not installed.")
ModuleNotFoundError: Linkify enabled but not installed.
←[91mThe full traceback has been saved in C:\Users\Willy\AppData\Local\Temp\sphinx-err-7gjhum5z.log, if you want to report the issue to the developers.←[39;49;00m
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Traceback (most recent call last):
  File "c:\users\willy\anaconda3\lib\site-packages\jupyter_book\sphinx.py", line 150, in build_sphinx
    app.build(force_all, filenames)
  File "c:\users\willy\anaconda3\lib\site-packages\sphinx\application.py", line 350, in build
    self.builder.build_update()
  File "c:\users\willy\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 292, in build_update
    self.build(to_build,
  File "c:\users\willy\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 306, in build
    updated_docnames = set(self.read())
  File "c:\users\willy\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 413, in read
    self._read_serial(docnames)
  File "c:\users\willy\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 434, in _read_serial
    self.read_doc(docname)
  File "c:\users\willy\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 474, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "c:\users\willy\anaconda3\lib\site-packages\sphinx\io.py", line 188, in read_doc
    pub.publish()
  File "c:\users\willy\anaconda3\lib\site-packages\docutils\core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "c:\users\willy\anaconda3\lib\site-packages\sphinx\io.py", line 108, in read
    self.parse()
  File "c:\users\willy\anaconda3\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "c:\users\willy\anaconda3\lib\site-packages\myst_nb\parser.py", line 49, in parse
    super().parse(inputstring, document=document)
  File "c:\users\willy\anaconda3\lib\site-packages\myst_parser\sphinx_parser.py", line 60, in parse
    tokens = parser.parse(inputstring, env)
  File "c:\users\willy\anaconda3\lib\site-packages\markdown_it\main.py", line 242, in parse
    self.core.process(state)
  File "c:\users\willy\anaconda3\lib\site-packages\markdown_it\parser_core.py", line 33, in process
    rule(state)
  File "c:\users\willy\anaconda3\lib\site-packages\markdown_it\rules_core\linkify.py", line 32, in linkify
    raise ModuleNotFoundError("Linkify enabled but not installed.")
ModuleNotFoundError: Linkify enabled but not installed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\willy\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\willy\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Willy\anaconda3\Scripts\jupyter-book.exe\__main__.py", line 7, in <module>
  File "c:\users\willy\anaconda3\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\willy\anaconda3\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\willy\anaconda3\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\willy\anaconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\willy\anaconda3\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\willy\anaconda3\lib\site-packages\jupyter_book\cli\main.py", line 316, in build
    builder_specific_actions(
  File "c:\users\willy\anaconda3\lib\site-packages\jupyter_book\cli\main.py", line 516, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError:
←[91m===============================================================================←[0m

There was an error in building your book. Look above for the cause.

←[91m===============================================================================←[0m

</details>

**Comment by kuchaale** [comment]
Try to do so. You can try to reinstall jupyterbook completely. [Here](https://github.com/executablebooks/jupyter-book/blob/v0.11.1/docs/requirements.txt) are the required libraries. It depends on version of jupyterbook you use though.

**Comment by stoeckel4code** [comment]
I fixed it by reinstalling a fresh environment and an older version of jupyter-book
